# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: neuro.proto
# Protobuf Python Version: 4.26.0-dev
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bneuro.proto\x12\x0ctext_process\"*\n\x0cNeuroRequest\x12\x0b\n\x03qid\x18\x01 \x01(\r\x12\r\n\x05query\x18\x02 \x01(\t\"<\n\x0bNeuroAnswer\x12\x0b\n\x03qid\x18\x01 \x01(\r\x12\x11\n\tembedding\x18\x02 \x03(\x02\x12\r\n\x05\x65rror\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'neuro_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._loaded_options = None
  _globals['_NEUROREQUEST']._serialized_start=29
  _globals['_NEUROREQUEST']._serialized_end=71
  _globals['_NEUROANSWER']._serialized_start=73
  _globals['_NEUROANSWER']._serialized_end=133
# @@protoc_insertion_point(module_scope)
